name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: list-1
        run: ls -la

      - name: checkout
        uses: actions/checkout@v2

      - name: copies
        run: |
          mkdir out
          cp index.html ./out

      - name: list-2
        run: ls -la

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out/