name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: list-2
        run: ls -la

      - name: checkout
        uses: actions/checkout@v2

      - name: list-2
        run: ls -la
